# Supply Chain Performance Analytics: Delivery Optimization, Order Profitability, and Operational Efficiency
## Supply Chain Management, Logistics, Operations Analytics, and Business Intelligence
## 1. Project Overview

The **Supply Chain Analytics: Inventory Management, Logistics Optimization, and Demand Forecasting** project aims to analyze supply chain operations using Python and the DataCo SMART Supply Chain dataset. The project focuses on examining order processing, product demand, inventory-related patterns, shipping performance, and delivery operations to identify inefficiencies and support data-driven business decisions.

The project involves collecting, cleaning, preprocessing, and analyzing supply chain data using Python libraries such as Pandas, NumPy, Matplotlib, and Seaborn. Exploratory Data Analysis (EDA) will be performed to understand order trends, product category performance, regional demand patterns, shipping costs, and delivery delays. Appropriate visualizations will be developed to identify operational trends, potential bottlenecks, and areas for improvement.

The analysis will focus on evaluating delivery performance, identifying factors associated with late shipments, examining demand patterns across product categories and geographical regions, and comparing shipping costs across different shipping methods. Where the available data supports it, time-series analysis and machine learning techniques may be explored to forecast future demand and improve inventory planning.

The primary objective is to transform raw supply chain data into meaningful insights that can help organizations improve delivery efficiency, reduce unnecessary logistics costs, plan inventory more effectively, and enhance overall operational performance. The entire analytical workflow will be implemented in Python, from data preprocessing and exploratory analysis to visualization and, where appropriate, predictive modeling.

## 2. Business Problem

Supply chain operations involve multiple interconnected activities, including order processing, product distribution, shipping, and delivery. Inefficiencies in these activities can contribute to delayed deliveries, inconsistent service performance, and reduced order profitability.

Without systematic analysis, businesses may find it difficult to identify which shipping methods, geographical regions, product categories, or order characteristics are associated with delivery delays or lower profitability.

This project addresses the following business problems:

* **Delivery Performance:** How can delivery delays and late-delivery risks be examined across shipping methods, regions, and order characteristics?
* **Shipping Efficiency:** Which shipping methods have different delivery durations or delivery performance?
* **Order Profitability:** How does order profitability vary across product categories, customer segments, and geographical regions?
* **Product Performance:** Which product categories and departments contribute most to sales and order profitability?
* **Customer Behavior:** How do customer segments and geographical characteristics relate to ordering patterns?
* **Operational Improvement:** Which areas should be investigated further to identify opportunities for improving delivery performance and profitability?

The analysis will identify patterns and associations in the available data. It will not assume that a particular factor causes delays or losses without sufficient evidence.

## 3. Project Objectives

The project will pursue the following measurable objectives.

### Objective 1: Data Quality Assessment and Cleaning

* Inspect the dataset's dimensions, data types, and column names.
* Identify missing values, duplicate records, inconsistent categories, and invalid values.
* Validate date and time fields.
* Investigate unusual values in sales, profit, shipping duration, and other numerical variables.
* Document the cleaning decisions and their impact on the dataset.

**Measurement:** Missing-value counts, duplicate counts, data-type corrections, invalid-value counts, and the number of records retained after cleaning.

### Objective 2: Order and Sales Performance Analysis

* Examine order volume and sales trends over time.
* Compare sales across product categories, departments, and geographical regions.
* Analyze the distribution of sales across customer segments.
* Identify high-volume product and order segments.

**Measurement:** Total sales, number of orders, average sales per order, sales growth where comparable periods are available, and category-wise sales contribution.

### Objective 3: Delivery Performance Analysis

* Compare actual and scheduled shipping durations where the relevant fields are available.
* Analyze delivery status across shipping methods.
* Calculate the late-delivery rate.
* Investigate late deliveries across regions, product categories, and customer segments.
* Examine delivery performance over time.

**Measurement:** Late-delivery rate, on-time delivery rate where supported by the available status definitions, average actual shipping duration, and delivery-duration variance.

### Objective 4: Shipping Efficiency Analysis

* Compare shipping methods based on delivery duration and delivery status.
* Investigate differences between scheduled and actual shipping durations.
* Examine the relationship between shipping mode and late-delivery risk.
* Identify shipping methods or segments that warrant further operational investigation.

**Measurement:** Average actual shipping duration, average difference between actual and scheduled duration, and late-delivery rate by shipping mode.

### Objective 5: Order Profitability Analysis

* Examine profit or benefit per order using the appropriate available financial fields.
* Identify product categories and departments with comparatively higher or lower profitability.
* Investigate the relationship between sales, discounts, and profitability where the required fields exist.
* Identify negative-profit records and examine their characteristics.

**Measurement:** Total recorded benefit per order, average benefit per order, percentage of negative-benefit records, and profitability by category and region.

### Objective 6: Customer and Geographical Analysis

* Examine order patterns across customer segments.
* Analyze sales and order distribution by customer destination.
* Compare delivery performance across geographical regions.
* Investigate the distribution of order activity across available customer groups.

**Measurement:** Number of unique customers, number of orders, average order value, sales by customer segment, and late-delivery rate by destination region.

### Objective 7: Statistical Analysis and Business Recommendations

* Explore relationships between numerical variables.
* Investigate differences in delivery performance across groups.
* Identify unusual observations and potential operational patterns.
* Summarize evidence-based recommendations for further investigation.

**Measurement:** Correlation coefficients where appropriate, descriptive statistics, group-level comparisons, and documented recommendations supported by the analysis.

---

## 4. Business Value & Use Case

The project is intended to demonstrate how data analytics can support supply chain performance monitoring and operational decision-making.

### Intended Stakeholders

**Supply Chain Managers**

* Monitor delivery performance and operational trends.
* Identify geographical or shipping segments requiring investigation.
* Support operational planning using historical patterns.

**Logistics and Transportation Analysts**

* Compare shipping methods and delivery durations.
* Investigate late-delivery patterns.
* Evaluate differences between scheduled and actual shipping durations.

**Business and Financial Analysts**

* Examine sales and profitability patterns.
* Identify product categories with lower recorded profitability.
* Support further investigation into negative-profit transactions.

**Customer Experience Teams**

* Understand delivery-status patterns that may affect customer experience.
* Identify customer or geographical segments with relatively high late-delivery rates.

**Operations Management**

* Use analytical evidence to prioritize improvement opportunities.
* Monitor KPIs consistently.
* Support decisions about where additional operational data or investigation may be required.

### Expected Business Value

The analysis is expected to provide:

* Better visibility into historical delivery performance.
* A structured approach to identifying potential operational inefficiencies.
* Improved understanding of order profitability across business segments.
* Evidence-based identification of areas requiring further investigation.
* Reproducible Python workflows for data preparation and analysis.

These are intended benefits, not confirmed outcomes. Actual findings and recommendations will be documented after the analysis is completed.

---

## 5. Dataset Information Source

### Dataset Name

**DataCo SMART Supply Chain for Big Data Analysis**

### Source

[Mendeley Data — DataCo SMART Supply Chain for Big Data Analysis](https://data.mendeley.com/datasets/8gx2fvg2k6/5)

In [18]:
df1 = pd.read_csv(r"F:\Project\SupplyChain\Project dataset\DataCoSupplyChainDataset.csv",encoding="latin1")
df2 = pd.read_csv(r"F:\Project\SupplyChain\Project dataset\tokenized_access_logs.csv",encoding="latin1")
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [29]:
import pandas as pd

print("First Dataset:")
print("Dataset Shape:", df1.shape)
print("Second Dataset:")
print("Dataset Shape:", df2.shape)

print("\nColumn Names:")
print("First Dataset:")
print(df1.columns.tolist())
print("Second Dataset:")
print(df2.columns.tolist())

print("\nData Types:")
print("First Dataset:")
print(df1.dtypes)
print("Second Dataset:")
print(df2.dtypes)

print("\nMissing Values:")
print("First Dataset:")
print(df1.isnull().sum().sort_values(ascending=False).head(15))
print("Second Dataset:")
print(df2.isnull().sum().sort_values(ascending=False).head(15))

print("First Dataset:")
print("\nDuplicate Rows:", df1.duplicated().sum())
print("Second Dataset:")
print("\nDuplicate Rows:", df2.duplicated().sum())

Dataset Shape: (180519, 53)
Dataset Shape: (469977, 8)

Column Names:
['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Image', 'Product Name', 'Product Price', 'Product Status', 'shipping date (DateOrders)', 'Shipping Mode']
['Product', 'Category', 'Date', 'Month', 'Hour', 'Department', 'ip', 'url']

Data Types:
Type                                 str
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                      str
Late_delivery_risk                 int64
Category Id                        int64
Category Name                        str
Customer City                        str
Customer Country                     str
Customer Email                       str
Customer Fname                       str
Customer Id                        int64
Customer Lname                       str
Customer Password                    str
Customer Segment                     str
Customer State                       str
Customer Street                      str
Customer Zipcode                 float64
Department Id                      int64
Department Name                      str
Latitude                         float64
Longitude                        float64
Market                               str
Order City                           str
Order Country                        str
Order Customer Id                  int64
order date (DateOrders)              str
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                         str
Order State                          str
Order Status                         str
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                        str
Product Name                         str
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)           str
Shipping Mode                        str
dtype: object
Product         str
Category        str
Date            str
Month           str
Hour          int64
Department      str
ip              str
url             str
dtype: object

Missing Values:
Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Days for shipment (scheduled)         0
Sales per customer                    0
Benefit per order                     0
Delivery Status                       0
Late_delivery_risk                    0
Customer City                         0
Customer Country                      0
Category Id                           0
Category Name                         0
Customer Fname                        0
Customer Email                        0
dtype: int64
Product       0
Category      0
Date          0
Month         0
Hour          0
Department    0
ip            0
url           0
dtype: int64

Duplicate Rows: 0

Duplicate Rows: 3249

First Five Records:
       Type  Days for shipping (real)  Days for shipment (scheduled)  \
0     DEBIT                         3                              4
1  TRANSFER                         5                              4
2      CASH                         4                              4
3     DEBIT                         3                              4
4   PAYMENT                         2                              4

   Benefit per order  Sales per customer   Delivery Status  \
0          91.250000          314.640015  Advance shipping
1        -249.089996          311.359985     Late delivery
2        -247.779999          309.720001  Shipping on time
3          22.860001          304.809998  Advance shipping
4         134.210007          298.250000  Advance shipping

   Late_delivery_risk  Category Id   Category Name Customer City  ...  \
0                   0           73  Sporting Goods        Caguas  ...
1                   1           73  Sporting Goods        Caguas  ...
2                   0           73  Sporting Goods      San Jose  ...
3                   0           73  Sporting Goods   Los Angeles  ...
4                   0           73  Sporting Goods        Caguas  ...

  Order Zipcode Product Card Id Product Category Id  Product Description  \
0           NaN            1360                  73                  NaN
1           NaN            1360                  73                  NaN
2           NaN            1360                  73                  NaN
3           NaN            1360                  73                  NaN
4           NaN            1360                  73                  NaN

                                  Product Image  Product Name Product Price  \
0  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
1  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
2  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
3  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
4  http://images.acmesports.sports/Smart+watch   Smart watch         327.75

  Product Status shipping date (DateOrders)   Shipping Mode
0              0             2/3/2018 22:56  Standard Class
1              0            1/18/2018 12:27  Standard Class
2              0            1/17/2018 12:06  Standard Class
3              0            1/16/2018 11:45  Standard Class
4              0            1/15/2018 11:24  Standard Class

[5 rows x 53 columns]
                                      Product             Category  \
0     adidas Brazuca 2017 Official Match Ball  baseball & softball
1       The North Face Women's Recon Backpack   hunting & shooting
2      adidas Kids' RG III Mid Football Cleat       featured shops
3  Under Armour Men's Compression EV SL Slide          electronics
4                 Pelican Sunstream 100 Kayak         water sports

            Date Month  Hour Department              ip  \
0  9/1/2017 6:00   Sep     6   fitness     37.97.182.65
1  9/1/2017 6:00   Sep     6  fan shop     206.56.112.1
2  9/1/2017 6:00   Sep     6   apparel    215.143.180.0
3  9/1/2017 6:00   Sep     6  footwear     206.56.112.1
4  9/1/2017 6:01   Sep     6  fan shop   136.108.56.242

                                                 url
0  /department/fitness/category/baseball%20&%20so...
1  /department/fan%20shop/category/hunting%20&%20...
2  /department/apparel/category/featured%20shops/...
3  /department/footwear/category/electronics/prod...
4  /department/fan%20shop/category/water%20sports...

In [31]:
print("First Dataset:")
print("Number of rows:", df1.shape[0])
print("Number of columns:", df1.shape[1])

print("Second Dataset:")
print("Number of rows:", df2.shape[0])
print("Number of columns:", df2.shape[1])

First Dataset:
Number of rows: 180519
Number of columns: 53
Second Dataset:
Number of rows: 469977
Number of columns: 8

In [20]:
df1.head(5)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [24]:
df2.head(5)

,Product,Category,Date,Month,Hour,Department,ip,url
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,Sep,6,fitness,37.97.182.65,/department/fitness/category/baseball%20&%20so...
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,Sep,6,fan shop,206.56.112.1,/department/fan%20shop/category/hunting%20&%20...
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,Sep,6,apparel,215.143.180.0,/department/apparel/category/featured%20shops/...
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,Sep,6,footwear,206.56.112.1,/department/footwear/category/electronics/prod...
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,Sep,6,fan shop,136.108.56.242,/department/fan%20shop/category/water%20sports...

In [32]:
print("First Dataset:")
df2.info()
print("Second Dataset:")
df2.info()

First Dataset:
<class 'pandas.DataFrame'>
RangeIndex: 469977 entries, 0 to 469976
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Product     469977 non-null  str
 1   Category    469977 non-null  str
 2   Date        469977 non-null  str
 3   Month       469977 non-null  str
 4   Hour        469977 non-null  int64
 5   Department  469977 non-null  str
 6   ip          469977 non-null  str
 7   url         469977 non-null  str
dtypes: int64(1), str(7)
memory usage: 114.9 MB
Second Dataset:
<class 'pandas.DataFrame'>
RangeIndex: 469977 entries, 0 to 469976
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Product     469977 non-null  str
 1   Category    469977 non-null  str
 2   Date        469977 non-null  str
 3   Month       469977 non-null  str
 4   Hour        469977 non-null  int64
 5   Department  469977 non-null  str
 6   ip          469977 non-null  str
 7   url         469977 non-null  str
dtypes: int64(1), str(7)
memory usage: 114.9 MB

## Initial Dataset Observations

The DataCo SMART Supply Chain dataset, obtained from Mendeley Data, contains structured supply chain information covering order transactions, product categories, customer details, sales, and shipping operations. It is designed to support supply chain analysis, data mining, and machine learning applications. The dataset also includes a separate file describing the available variables.

Based on the dataset description, the following initial observations have been identified for further investigation:

1. **Dataset Structure:** The primary dataset is provided in CSV format and contains a large volume of transactional records. Its size makes Python libraries such as Pandas and NumPy suitable for data processing and analysis.

2. **Order and Sales Information:** The dataset includes order-related information and sales measures that can be used to investigate order patterns, sales performance, and product demand across categories and regions.

3. **Product and Customer Information:** Product categories, customer attributes, and geographical details provide opportunities to compare purchasing patterns and identify important customer and regional segments.

4. **Shipping and Delivery Information:** Shipping methods, actual and scheduled shipping durations, delivery status, and late-delivery indicators can support an assessment of delivery performance and potential logistics bottlenecks.

5. **Financial Information:** Available sales, profit-related, and shipping-cost fields can be examined to understand financial performance and investigate relationships between logistics operations and profitability.

6. **Potential Data-Quality Issues:** Missing values, duplicate records, inconsistent data types, invalid values, and unusual observations will be investigated during preprocessing. These issues should not be assumed to exist until they have been checked in the actual dataset.

7. **Analytical Suitability:** The dataset appears suitable for exploratory data analysis, delivery-performance evaluation, product and regional analysis, and investigation of shipping costs. Predictive modeling and demand forecasting will depend on data quality, feature availability, and the suitability of the historical data.

8. **Inventory Analysis Limitation:** The dataset description emphasizes transactional, product, customer, sales, and shipping information. Direct inventory levels, stock availability, and warehouse replenishment records must be verified before attempting detailed inventory optimization.

These preliminary observations will guide the next stage of the project, which involves inspecting the dataset using Python, assessing data quality, identifying relevant variables, and determining the final analytical approach.